= provoly-dependencies

Dependencies for the provoly project

[horizontal]
Type:: application
Version:: 0.1.15
Application version:: 1.0.0

== Dependencies

Here are the chart dependencies :

[%autowidth, stripes=even]
|===
|Name |Repository | Version| Condition

a|`akhq`
|https://akhq.io/
|0.24.0
a|`akhq.enabled`

a|`keycloakx`
|https://codecentric.github.io/helm-charts
|2.2.2
a|`keycloakx.enabled`

a|`paas-kuzzle`
|https://kuzzleio.github.io/helm-charts/
|2.1.1
a|`kuzzle.enabled`

a|`node-red`
|https://schwarzit.github.io/node-red-chart/
|0.28.0
a|`nodered.enabled`

|===

== Chart values


=== Global



|===

| Name | Description | Default value

a| `kubeVersion`
| @section Common parameters + 
@param kubeVersion Force target Kubernetes version (using Helm capabilities if not set)
a| 

a| `nameOverride`
| @param nameOverride String to partially override common.names.fullname
a| 

a| `fullnameOverride`
| @param fullnameOverride String to fully override common.names.fullname
a| 

a| `namespaceOverride`
| @param namespaceOverride String to fully override common.names.namespace
a| 

a| `enableServiceLinks`
| @param enableServiceLinks If set to false, disable Kubernetes service links in the pod spec + 
accessing-the-service
a| true

a| `dnsPolicy`
| @param dnsPolicy DNS Policy for pod + 
ref: https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/ + 
E.g. + 
dnsPolicy: ClusterFirst
a| 

a| `clusterDomain`
| @param clusterDomain Default Kubernetes cluster domain
a| cluster.local

a| `extraDeploy`
| @param extraDeploy Array of extra objects to deploy with the release
a| 

a| `customCaExistingSecret`
| Custom Certificates + 
@param customCaExistingSecret Name of the secret containing the Keycloak custom CA certificates. The secret will be mounted as a directory and configured using KC_TRUSTSTORE_PATHS. + 
https://www.keycloak.org/server/keycloak-truststore + 
Could be created like this: kubectl create secret generic secretName --from-file=./certificateToMerge.pem
a| 

a| `adminRealm`
| @param adminRealm Name of the admin realm
a| master

a| `production`
| @param production Run Keycloak in production mode. TLS configuration is required except when using proxy=edge.
a| false

a| `proxyHeaders`
| @param proxyHeaders Set Keycloak proxy headers
a| 

a| `proxy`
| @param proxy reverse Proxy mode edge, reencrypt, passthrough or none + 
DEPRECATED: use proxyHeaders instead + 
ref: https://www.keycloak.org/server/reverseproxy
a| 

a| `httpRelativePath`
| @param httpRelativePath Set the path relative to '/' for serving resources. Useful if you are migrating from older version which were using '/auth/' + 
_default_context_path_changed
a| /

a| `configuration`
| Keycloak Service Discovery settings + 
cluster-configuration + 
@param configuration Keycloak Configuration. Auto-generated based on other parameters when not specified + 
Specify content for keycloak.conf + 
NOTE: This will override configuring Keycloak based on environment variables (including those set by the chart) + 
The keycloak.conf is auto-generated based on other parameters when this parameter is not specified + 
Example: + 
configuration: \|- + 
foo: bar + 
baz:
a| 

a| `existingConfigmap`
| @param existingConfigmap Name of existing ConfigMap with Keycloak configuration + 
NOTE: When it's set the configuration parameter is ignored
a| 

a| `extraStartupArgs`
| @param extraStartupArgs Extra default startup args
a| 

a| `enableDefaultInitContainers`
| @param enableDefaultInitContainers Deploy default init containers + 
Disable this parameter could be helpful for 3rd party images e.g native Keycloak image.
a| true

a| `initdbScriptsConfigMap`
| @param initdbScriptsConfigMap ConfigMap with the initdb scripts (Note: Overrides `initdbScripts`)
a| 

a| `command`
| @param command Override default container command (useful when using custom images)
a| 

a| `args`
| @param args Override default container args (useful when using custom images)
a| 

a| `extraEnvVars`
| @param extraEnvVars Extra environment variables to be set on Keycloak container + 
Example: + 
extraEnvVars: + 
- name: FOO + 
value: "bar"
a| 

a| `extraEnvVarsCM`
| @param extraEnvVarsCM Name of existing ConfigMap containing extra env vars
a| 

a| `extraEnvVarsSecret`
| @param extraEnvVarsSecret Name of existing Secret containing extra env vars
a| 

a| `replicaCount`
| @section Keycloak statefulset parameters + 
@param replicaCount Number of Keycloak replicas to deploy
a| 1

a| `revisionHistoryLimitCount`
| @param revisionHistoryLimitCount Number of controller revisions to keep
a| 10

a| `extraContainerPorts`
| @param extraContainerPorts Optionally specify extra list of additional port-mappings for Keycloak container
a| 

a| `resourcesPreset`
| Keycloak resource requests and limits + 
ref: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/ + 
@param resourcesPreset Set container resources according to one common preset (allowed values: none, nano, micro, small, medium, large, xlarge, 2xlarge). This is ignored if resources is set (resources is recommended for production). + 
L15
a| small

a| `automountServiceAccountToken`
| @param automountServiceAccountToken Mount Service Account token in pod
a| true

a| `hostAliases`
| @param hostAliases Deployment pod host aliases + 
https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/
a| 

a| `podAffinityPreset`
| @param podAffinityPreset Pod affinity preset. Ignored if `affinity` is set. Allowed values: `soft` or `hard` + 
inter-pod-affinity-and-anti-affinity
a| 

a| `podAntiAffinityPreset`
| @param podAntiAffinityPreset Pod anti-affinity preset. Ignored if `affinity` is set. Allowed values: `soft` or `hard` + 
inter-pod-affinity-and-anti-affinity
a| soft

a| `tolerations`
| @param tolerations Tolerations for pod assignment + 
ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
a| 

a| `topologySpreadConstraints`
| @param topologySpreadConstraints Topology Spread Constraints for pod assignment spread across your cluster among failure-domains. Evaluated as a template + 
spread-constraints-for-pods
a| 

a| `podManagementPolicy`
| @param podManagementPolicy Pod management policy for the Keycloak statefulset
a| Parallel

a| `priorityClassName`
| @param priorityClassName Keycloak pods' Priority Class Name + 
ref: https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/
a| 

a| `schedulerName`
| @param schedulerName Use an alternate scheduler, e.g. "stork". + 
ref: https://kubernetes.io/docs/tasks/administer-cluster/configure-multiple-schedulers/
a| 

a| `terminationGracePeriodSeconds`
| @param terminationGracePeriodSeconds Seconds Keycloak pod needs to terminate gracefully + 
termination-of-pods
a| 

a| `minReadySeconds`
| @param minReadySeconds How many seconds a pod needs to be ready before killing the next, during update
a| 0

a| `extraVolumes`
| @param extraVolumes Optionally specify extra list of additional volumes for Keycloak pods
a| 

a| `extraVolumeMounts`
| @param extraVolumeMounts Optionally specify extra list of additional volumeMounts for Keycloak container(s)
a| 

a| `initContainers`
| @param initContainers Add additional init containers to the Keycloak pods + 
Example: + 
initContainers: + 
- name: your-image-name + 
image: your-image + 
imagePullPolicy: Always + 
ports: + 
- name: portname + 
containerPort: 1234
a| 

a| `sidecars`
| @param sidecars Add additional sidecar containers to the Keycloak pods + 
Example: + 
sidecars: + 
- name: your-image-name + 
image: your-image + 
imagePullPolicy: Always + 
ports: + 
- name: portname + 
containerPort: 1234
a| 

|===


==== global

Copyright Broadcom, Inc. All Rights Reserved. + 
SPDX-License-Identifier: APACHE-2.0 + 
@section Global parameters + 
Global Docker image parameters + 
Please, note that this will override the image parameters, including dependencies, configured to use the global value + 
Current available global Docker image parameters: imageRegistry, imagePullSecrets and storageClass + 
@param global.imageRegistry Global Docker image registry + 
@param global.imagePullSecrets Global Docker registry secret names as an array + 
@param global.defaultStorageClass Global default StorageClass for Persistent Volume(s) + 
@param global.storageClass DEPRECATED: use global.defaultStorageClass instead

|===

| Name | Description | Default value

a| `imageRegistry`
| 
a| 

a| `imagePullSecrets`
| E.g. + 
imagePullSecrets: + 
- myRegistryKeySecretName
a| 

a| `defaultStorageClass`
| 
a| 

a| `storageClass`
| 
a| 

|===


===== global.compatibility

Compatibility adaptations for Kubernetes platforms



====== global.compatibility.openshift

Compatibility adaptations for Openshift






==== commonLabels

@param commonLabels Labels to add to all deployed objects




==== commonAnnotations

@param commonAnnotations Annotations to add to all deployed objects




==== dnsConfig

@param dnsConfig DNS Configuration pod + 
ref: https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/ + 
E.g. + 
dnsConfig: + 
options: + 
- name: ndots + 
value: "4"




==== diagnosticMode

Enable diagnostic mode in the statefulset

|===

| Name | Description | Default value

a| `enabled`
| @param diagnosticMode.enabled Enable diagnostic mode (all probes will be disabled and the command will be overridden)
a| false

a| `command`
| @param diagnosticMode.command Command to override all containers in the the statefulset
a| sleep

a| `args`
| @param diagnosticMode.args Args to override all containers in the the statefulset
a| infinity

|===



==== image

@section Keycloak parameters + 
Bitnami Keycloak image version + 
ref: https://hub.docker.com/r/bitnami/keycloak/tags/ + 
@param image.registry [default: REGISTRY_NAME] Keycloak image registry + 
@param image.repository [default: REPOSITORY_NAME/keycloak] Keycloak image repository + 
@skip image.tag Keycloak image tag (immutable tags are recommended) + 
@param image.digest Keycloak image digest in the way sha256:aa.... Please note this parameter, if set, will override the tag + 
@param image.pullPolicy Keycloak image pull policy + 
@param image.pullSecrets Specify docker-registry secret names as an array + 
@param image.debug Specify if debug logs should be enabled

|===

| Name | Description | Default value

a| `registry`
| 
a| docker.io

a| `repository`
| 
a| bitnami/keycloak

a| `tag`
| 
a| 25.0.2-debian-12-r0

a| `digest`
| 
a| 

a| `pullPolicy`
| Specify a imagePullPolicy + 
Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent' + 
pre-pulled-images
a| IfNotPresent

a| `pullSecrets`
| Optionally specify an array of imagePullSecrets. + 
Secrets must be manually created in the namespace. + 
ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/ + 
Example: + 
pullSecrets: + 
- myRegistryKeySecretName
a| 

a| `debug`
| Set to true if you would like to see extra information on logs
a| false

|===



==== auth

Keycloak authentication parameters + 
admin-credentials

|===

| Name | Description | Default value

a| `adminUser`
| @param auth.adminUser Keycloak administrator user
a| user

a| `adminPassword`
| @param auth.adminPassword Keycloak administrator password for the new user
a| 

a| `existingSecret`
| @param auth.existingSecret Existing secret containing Keycloak admin password
a| 

a| `passwordSecretKey`
| @param auth.passwordSecretKey Key where the Keycloak admin password is being stored inside the existing secret.
a| 

|===


===== auth.annotations

@param auth.annotations Additional custom annotations for Keycloak auth secret object





==== tls

HTTPS settings + 
tls-encryption

|===

| Name | Description | Default value

a| `enabled`
| @param tls.enabled Enable TLS encryption. Required for HTTPs traffic.
a| false

a| `autoGenerated`
| @param tls.autoGenerated Generate automatically self-signed TLS certificates. Currently only supports PEM certificates
a| false

a| `existingSecret`
| @param tls.existingSecret Existing secret containing the TLS certificates per Keycloak replica + 
Create this secret following the steps below: + 
_setting_up_ssl) + 
2) Rename your truststore to `keycloak.truststore.jks` or use a different name overwriting the value 'tls.truststoreFilename'. + 
3) Rename your keystores to `keycloak.keystore.jks` or use a different name overwriting the value 'tls.keystoreFilename'. + 
4) Run the command below where SECRET_NAME is the name of the secret you want to create: + 
kubectl create secret generic SECRET_NAME --from-file=./keycloak.truststore.jks --from-file=./keycloak.keystore.jks + 
NOTE: If usePem enabled, make sure the PEM key and cert are named 'tls.key' and 'tls.crt' respectively.
a| 

a| `usePem`
| @param tls.usePem Use PEM certificates as input instead of PKS12/JKS stores + 
If "true", the Keycloak chart will look for the files keycloak.key and keycloak.crt inside the secret provided with 'existingSecret'.
a| false

a| `truststoreFilename`
| @param tls.truststoreFilename Truststore filename inside the existing secret
a| keycloak.truststore.jks

a| `keystoreFilename`
| @param tls.keystoreFilename Keystore filename inside the existing secret
a| keycloak.keystore.jks

a| `keystorePassword`
| @param tls.keystorePassword Password to access the keystore when it's password-protected
a| 

a| `truststorePassword`
| @param tls.truststorePassword Password to access the truststore when it's password-protected
a| 

a| `passwordsSecret`
| @param tls.passwordsSecret Secret containing the Keystore and Truststore passwords.
a| 

|===



==== spi

SPI TLS settings + 
ref: https://www.keycloak.org/server/keycloak-truststore

|===

| Name | Description | Default value

a| `existingSecret`
| @param spi.existingSecret Existing secret containing the Keycloak truststore for SPI connection over HTTPS/TLS + 
Create this secret following the steps below: + 
1) Rename your truststore to `keycloak-spi.truststore.jks` or use a different name overwriting the value 'spi.truststoreFilename'. + 
2) Run the command below where SECRET_NAME is the name of the secret you want to create: + 
kubectl create secret generic SECRET_NAME --from-file=./keycloak-spi.truststore.jks --from-file=./keycloak.keystore.jks
a| 

a| `truststorePassword`
| @param spi.truststorePassword Password to access the truststore when it's password-protected
a| 

a| `truststoreFilename`
| @param spi.truststoreFilename Truststore filename inside the existing secret
a| keycloak-spi.truststore.jks

a| `passwordsSecret`
| @param spi.passwordsSecret Secret containing the SPI Truststore passwords.
a| 

a| `hostnameVerificationPolicy`
| @param spi.hostnameVerificationPolicy Verify the hostname of the server's certificate. Allowed values: "ANY", "WILDCARD", "STRICT".
a| 

|===



==== initdbScripts

@param initdbScripts Dictionary of initdb scripts + 
Specify dictionary of scripts to be run at first boot + 
initializing-a-new-instance + 
Example: + 
initdbScripts: + 
my_init_script.sh: \| + 
!/bin/bash + 
echo "Do something."




==== containerPorts

@param containerPorts.http Keycloak HTTP container port + 
@param containerPorts.https Keycloak HTTPS container port

|===

| Name | Description | Default value

a| `http`
| 
a| 8080

a| `https`
| 
a| 8443

|===



==== statefulsetAnnotations

@param statefulsetAnnotations Optionally add extra annotations on the statefulset resource




==== podSecurityContext

Keycloak pods' SecurityContext + 
set-the-security-context-for-a-pod + 
@param podSecurityContext.enabled Enabled Keycloak pods' Security Context + 
@param podSecurityContext.fsGroupChangePolicy Set filesystem group change policy + 
@param podSecurityContext.sysctls Set kernel settings using the sysctl interface + 
@param podSecurityContext.supplementalGroups Set filesystem extra groups + 
@param podSecurityContext.fsGroup Set Keycloak pod's Security Context fsGroup

|===

| Name | Description | Default value

a| `enabled`
| 
a| true

a| `fsGroupChangePolicy`
| 
a| Always

a| `sysctls`
| 
a| 

a| `supplementalGroups`
| 
a| 

a| `fsGroup`
| 
a| 1001

|===



==== containerSecurityContext

Keycloak containers' Security Context + 
set-the-security-context-for-a-container + 
@param containerSecurityContext.enabled Enabled containers' Security Context + 
@param containerSecurityContext.seLinuxOptions [object,nullable] Set SELinux options in container + 
@param containerSecurityContext.runAsUser Set containers' Security Context runAsUser + 
@param containerSecurityContext.runAsGroup Set containers' Security Context runAsGroup + 
@param containerSecurityContext.runAsNonRoot Set container's Security Context runAsNonRoot + 
@param containerSecurityContext.privileged Set container's Security Context privileged + 
@param containerSecurityContext.readOnlyRootFilesystem Set container's Security Context readOnlyRootFilesystem + 
@param containerSecurityContext.allowPrivilegeEscalation Set container's Security Context allowPrivilegeEscalation + 
@param containerSecurityContext.capabilities.drop List of capabilities to be dropped + 
@param containerSecurityContext.seccompProfile.type Set container's Security Context seccomp profile

|===

| Name | Description | Default value

a| `enabled`
| 
a| true

a| `runAsUser`
| 
a| 1001

a| `runAsGroup`
| 
a| 1001

a| `runAsNonRoot`
| 
a| true

a| `privileged`
| 
a| false

a| `readOnlyRootFilesystem`
| 
a| true

a| `allowPrivilegeEscalation`
| 
a| false

|===


===== containerSecurityContext.seLinuxOptions






===== containerSecurityContext.capabilities






===== containerSecurityContext.seccompProfile







==== resources

@param resources Set container requests and limits for different resources like CPU or memory (essential for production workloads) + 
Example: + 
resources: + 
requests: + 
cpu: 2 + 
memory: 512Mi + 
limits: + 
cpu: 3 + 
memory: 1024Mi




==== livenessProbe

Configure extra options for Keycloak containers' liveness, readiness and startup probes + 
configure-probes + 
@param livenessProbe.enabled Enable livenessProbe on Keycloak containers + 
@param livenessProbe.initialDelaySeconds Initial delay seconds for livenessProbe + 
@param livenessProbe.periodSeconds Period seconds for livenessProbe + 
@param livenessProbe.timeoutSeconds Timeout seconds for livenessProbe + 
@param livenessProbe.failureThreshold Failure threshold for livenessProbe + 
@param livenessProbe.successThreshold Success threshold for livenessProbe

|===

| Name | Description | Default value

a| `enabled`
| 
a| true

a| `initialDelaySeconds`
| 
a| 300

a| `periodSeconds`
| 
a| 1

a| `timeoutSeconds`
| 
a| 5

a| `failureThreshold`
| 
a| 3

a| `successThreshold`
| 
a| 1

|===



==== readinessProbe

@param readinessProbe.enabled Enable readinessProbe on Keycloak containers + 
@param readinessProbe.initialDelaySeconds Initial delay seconds for readinessProbe + 
@param readinessProbe.periodSeconds Period seconds for readinessProbe + 
@param readinessProbe.timeoutSeconds Timeout seconds for readinessProbe + 
@param readinessProbe.failureThreshold Failure threshold for readinessProbe + 
@param readinessProbe.successThreshold Success threshold for readinessProbe

|===

| Name | Description | Default value

a| `enabled`
| 
a| true

a| `initialDelaySeconds`
| 
a| 30

a| `periodSeconds`
| 
a| 10

a| `timeoutSeconds`
| 
a| 1

a| `failureThreshold`
| 
a| 3

a| `successThreshold`
| 
a| 1

|===



==== startupProbe

When enabling this, make sure to set initialDelaySeconds to 0 for livenessProbe and readinessProbe + 
@param startupProbe.enabled Enable startupProbe on Keycloak containers + 
@param startupProbe.initialDelaySeconds Initial delay seconds for startupProbe + 
@param startupProbe.periodSeconds Period seconds for startupProbe + 
@param startupProbe.timeoutSeconds Timeout seconds for startupProbe + 
@param startupProbe.failureThreshold Failure threshold for startupProbe + 
@param startupProbe.successThreshold Success threshold for startupProbe

|===

| Name | Description | Default value

a| `enabled`
| 
a| false

a| `initialDelaySeconds`
| 
a| 30

a| `periodSeconds`
| 
a| 5

a| `timeoutSeconds`
| 
a| 1

a| `failureThreshold`
| 
a| 60

a| `successThreshold`
| 
a| 1

|===



==== customLivenessProbe

@param customLivenessProbe Custom Liveness probes for Keycloak




==== customReadinessProbe

@param customReadinessProbe Custom Rediness probes Keycloak




==== customStartupProbe

@param customStartupProbe Custom Startup probes for Keycloak




==== lifecycleHooks

@param lifecycleHooks LifecycleHooks to set additional configuration at startup




==== podLabels

@param podLabels Extra labels for Keycloak pods + 
ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/




==== podAnnotations

@param podAnnotations Annotations for Keycloak pods + 
ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/




==== nodeAffinityPreset

Node affinity preset + 
node-affinity

|===

| Name | Description | Default value

a| `type`
| @param nodeAffinityPreset.type Node affinity preset type. Ignored if `affinity` is set. Allowed values: `soft` or `hard`
a| 

a| `key`
| @param nodeAffinityPreset.key Node label key to match. Ignored if `affinity` is set. + 
E.g. + 
key: "kubernetes.io/e2e-az-name"
a| 

a| `values`
| @param nodeAffinityPreset.values Node label values to match. Ignored if `affinity` is set. + 
E.g. + 
values: + 
- e2e-az1 + 
- e2e-az2
a| 

|===



==== affinity

@param affinity Affinity for pod assignment + 
affinity-and-anti-affinity




==== nodeSelector

@param nodeSelector Node labels for pod assignment + 
ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/




==== updateStrategy

@param updateStrategy.type Keycloak statefulset strategy type + 
@param updateStrategy.rollingUpdate Keycloak statefulset rolling update configuration parameters + 
update-strategies



===== updateStrategy.rollingUpdate







==== service

@section Exposure parameters + 
Service configuration

|===

| Name | Description | Default value

a| `type`
| @param service.type Kubernetes service type
a| ClusterIP

a| `sessionAffinity`
| @param service.sessionAffinity Control where client requests go, to the same pod or round-robin + 
Values: ClientIP or None + 
ref: https://kubernetes.io/docs/concepts/services-networking/service/
a| None

a| `clusterIP`
| @param service.clusterIP Keycloak service clusterIP IP + 
e.g: + 
clusterIP: None
a| 

a| `loadBalancerIP`
| @param service.loadBalancerIP loadBalancerIP for the SuiteCRM Service (optional, cloud specific) + 
type-loadbalancer
a| 

a| `loadBalancerSourceRanges`
| @param service.loadBalancerSourceRanges Address that are allowed when service is LoadBalancer + 
restrict-access-for-loadbalancer-service + 
Example: + 
loadBalancerSourceRanges: + 
- 10.10.10.0/24
a| 

a| `externalTrafficPolicy`
| @param service.externalTrafficPolicy Enable client source IP preservation + 
preserving-the-client-source-ip
a| Cluster

a| `extraPorts`
| @param service.extraPorts Extra port to expose on Keycloak service
a| 

a| `extraHeadlessPorts`
| DEPRECATED service.extraHeadlessPorts will be removed in a future release, please use service.headless.extraPorts instead + 
@param service.extraHeadlessPorts Extra ports to expose on Keycloak headless service
a| 

|===


===== service.http

@param service.http.enabled Enable http port on service




===== service.ports

@param service.ports.http Keycloak service HTTP port + 
@param service.ports.https Keycloak service HTTPS port

|===

| Name | Description | Default value

a| `http`
| 
a| 80

a| `https`
| 
a| 443

|===



===== service.nodePorts

@param service.nodePorts [object] Specify the nodePort values for the LoadBalancer and NodePort service types. + 
type-nodeport

|===

| Name | Description | Default value

a| `http`
| 
a| 

a| `https`
| 
a| 

|===



===== service.sessionAffinityConfig

@param service.sessionAffinityConfig Additional settings for the sessionAffinity + 
sessionAffinityConfig: + 
clientIP: + 
timeoutSeconds: 300




===== service.annotations

@param service.annotations Additional custom annotations for Keycloak service




===== service.headless

Headless service properties



====== service.headless.annotations

@param service.headless.annotations Annotations for the headless service.






==== ingress

Keycloak ingress parameters + 
ref: https://kubernetes.io/docs/concepts/services-networking/ingress/

|===

| Name | Description | Default value

a| `enabled`
| @param ingress.enabled Enable ingress record generation for Keycloak
a| false

a| `ingressClassName`
| @param ingress.ingressClassName IngressClass that will be be used to implement the Ingress (Kubernetes 1.18+) + 
This is supported in Kubernetes 1.18+ and required if you have more than one IngressClass marked as the default for your cluster . + 
ref: https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/
a| 

a| `pathType`
| @param ingress.pathType Ingress path type
a| ImplementationSpecific

a| `apiVersion`
| @param ingress.apiVersion Force Ingress API version (automatically detected if not set)
a| 

a| `controller`
| @param ingress.controller The ingress controller type. Currently supports `default` and `gce` + 
leave as `default` for most ingress controllers. + 
set to `gce` if using the GCE ingress controller
a| default

a| `hostname`
| @param ingress.hostname Default host for the ingress record (evaluated as template)
a| keycloak.local

a| `path`
| @param ingress.path [string] Default path for the ingress record (evaluated as template)
a| {{ .Values.httpRelativePath }}

a| `servicePort`
| @param ingress.servicePort Backend service port to use + 
Default is http. Alternative is https.
a| http

a| `tls`
| @param ingress.tls Enable TLS configuration for the host defined at `ingress.hostname` parameter + 
TLS certificates will be retrieved from a TLS secret with name: `{{- printf "%s-tls" (tpl .Values.ingress.hostname .) }}` + 
You can: + 
- Use the `ingress.secrets` parameter to create this TLS secret + 
- Rely on cert-manager to create it by setting the corresponding annotations + 
- Rely on Helm to create self-signed certificates by setting `ingress.selfSigned=true`
a| false

a| `selfSigned`
| @param ingress.selfSigned Create a TLS secret for this ingress record using self-signed certificates generated by Helm
a| false

a| `extraHosts`
| @param ingress.extraHosts An array with additional hostname(s) to be covered with the ingress record + 
e.g: + 
extraHosts: + 
- name: keycloak.local + 
path: /
a| 

a| `extraPaths`
| @param ingress.extraPaths Any additional arbitrary paths that may need to be added to the ingress under the main host. + 
For example: The ALB ingress controller requires a special rule for handling SSL redirection. + 
extraPaths: + 
- path: /* + 
backend: + 
serviceName: ssl-redirect + 
servicePort: use-annotation
a| 

a| `extraTls`
| @param ingress.extraTls The tls configuration for additional hostnames to be covered with this ingress record. + 
tls + 
extraTls: + 
- hosts: + 
- keycloak.local + 
secretName: keycloak.local-tls
a| 

a| `secrets`
| @param ingress.secrets If you're providing your own certificates, please use this to add the certificates as secrets + 
key and certificate should start with -----BEGIN CERTIFICATE----- or + 
-----BEGIN RSA PRIVATE KEY----- + 
name should line up with a tlsSecret set further up + 
If you're using cert-manager, this is unneeded, as it will create the secret for you if it is not set + 
It is also possible to create and manage the certificates outside of this helm chart + 
Please see README.md for more information + 
e.g: + 
- name: keycloak.local-tls + 
key: + 
certificate:
a| 

a| `extraRules`
| @param ingress.extraRules Additional rules to be covered with this ingress record + 
ingress-rules + 
e.g: + 
extraRules: + 
- host: airflow.local + 
http: + 
path: / + 
backend: + 
service: + 
name: airflow-svc + 
port: + 
name: http
a| 

|===


===== ingress.annotations

@param ingress.annotations [object] Additional annotations for the Ingress resource. To enable certificate autogeneration, place here your cert-manager annotations. + 
Use this parameter to set the required annotations for cert-manager, see + 
supported-annotations + 
e.g: + 
annotations: + 
kubernetes.io/ingress.class: nginx + 
cert-manager.io/cluster-issuer: cluster-issuer-name




===== ingress.labels

@param ingress.labels Additional labels for the Ingress resource. + 
e.g: + 
labels: + 
app: keycloak





==== adminIngress

Keycloak admin ingress parameters + 
ref: https://kubernetes.io/docs/user-guide/ingress/

|===

| Name | Description | Default value

a| `enabled`
| @param adminIngress.enabled Enable admin ingress record generation for Keycloak
a| false

a| `ingressClassName`
| @param adminIngress.ingressClassName IngressClass that will be be used to implement the Ingress (Kubernetes 1.18+) + 
This is supported in Kubernetes 1.18+ and required if you have more than one IngressClass marked as the default for your cluster . + 
ref: https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/
a| 

a| `pathType`
| @param adminIngress.pathType Ingress path type
a| ImplementationSpecific

a| `apiVersion`
| @param adminIngress.apiVersion Force Ingress API version (automatically detected if not set)
a| 

a| `controller`
| @param adminIngress.controller The ingress controller type. Currently supports `default` and `gce` + 
leave as `default` for most ingress controllers. + 
set to `gce` if using the GCE ingress controller
a| default

a| `hostname`
| @param adminIngress.hostname Default host for the admin ingress record (evaluated as template)
a| keycloak.local

a| `path`
| @param adminIngress.path [string] Default path for the admin ingress record (evaluated as template)
a| {{ .Values.httpRelativePath }}

a| `servicePort`
| @param adminIngress.servicePort Backend service port to use + 
Default is http. Alternative is https.
a| http

a| `tls`
| @param adminIngress.tls Enable TLS configuration for the host defined at `adminIngress.hostname` parameter + 
TLS certificates will be retrieved from a TLS secret with name: `{{- printf "%s-tls" (tpl .Values.adminIngress.hostname .) }}` + 
You can: + 
- Use the `adminIngress.secrets` parameter to create this TLS secret + 
- Rely on cert-manager to create it by setting the corresponding annotations + 
- Rely on Helm to create self-signed certificates by setting `adminIngress.selfSigned=true`
a| false

a| `selfSigned`
| @param adminIngress.selfSigned Create a TLS secret for this ingress record using self-signed certificates generated by Helm
a| false

a| `extraHosts`
| @param adminIngress.extraHosts An array with additional hostname(s) to be covered with the admin ingress record + 
e.g: + 
extraHosts: + 
- name: keycloak.local + 
path: /
a| 

a| `extraPaths`
| @param adminIngress.extraPaths Any additional arbitrary paths that may need to be added to the admin ingress under the main host. + 
For example: The ALB ingress controller requires a special rule for handling SSL redirection. + 
extraPaths: + 
- path: /* + 
backend: + 
serviceName: ssl-redirect + 
servicePort: use-annotation
a| 

a| `extraTls`
| @param adminIngress.extraTls The tls configuration for additional hostnames to be covered with this ingress record. + 
tls + 
extraTls: + 
- hosts: + 
- keycloak.local + 
secretName: keycloak.local-tls
a| 

a| `secrets`
| @param adminIngress.secrets If you're providing your own certificates, please use this to add the certificates as secrets + 
key and certificate should start with -----BEGIN CERTIFICATE----- or + 
-----BEGIN RSA PRIVATE KEY----- + 
name should line up with a tlsSecret set further up + 
If you're using cert-manager, this is unneeded, as it will create the secret for you if it is not set + 
It is also possible to create and manage the certificates outside of this helm chart + 
Please see README.md for more information + 
e.g: + 
- name: keycloak.local-tls + 
key: + 
certificate:
a| 

a| `extraRules`
| @param adminIngress.extraRules Additional rules to be covered with this ingress record + 
ingress-rules + 
e.g: + 
extraRules: + 
- host: airflow.local + 
http: + 
path: / + 
backend: + 
service: + 
name: airflow-svc + 
port: + 
name: http
a| 

|===


===== adminIngress.annotations

@param adminIngress.annotations [object] Additional annotations for the Ingress resource. To enable certificate autogeneration, place here your cert-manager annotations. + 
Use this parameter to set the required annotations for cert-manager, see + 
supported-annotations + 
e.g: + 
annotations: + 
kubernetes.io/ingress.class: nginx + 
cert-manager.io/cluster-issuer: cluster-issuer-name




===== adminIngress.labels

@param adminIngress.labels Additional labels for the Ingress resource. + 
e.g: + 
labels: + 
app: keycloak





==== networkPolicy

Network Policy configuration + 
ref: https://kubernetes.io/docs/concepts/services-networking/network-policies/

|===

| Name | Description | Default value

a| `enabled`
| @param networkPolicy.enabled Specifies whether a NetworkPolicy should be created
a| true

a| `allowExternal`
| @param networkPolicy.allowExternal Don't require server label for connections + 
The Policy model to apply. When set to false, only pods with the correct + 
server label will have network access to the ports server is listening + 
on. When true, server will accept connections from any source + 
(with the correct destination port).
a| true

a| `allowExternalEgress`
| @param networkPolicy.allowExternalEgress Allow the pod to access any range of port and all destinations.
a| true

a| `kubeAPIServerPorts`
| @param networkPolicy.kubeAPIServerPorts [array] List of possible endpoints to kube-apiserver (limit to your cluster settings to increase security)
a| 443.6443.8443

a| `extraIngress`
| @param networkPolicy.extraIngress [array] Add extra ingress rules to the NetworkPolicy + 
e.g: + 
extraIngress: + 
- ports: + 
- port: 1234 + 
from: + 
- podSelector: + 
- matchLabels: + 
- role: frontend + 
- podSelector: + 
- matchExpressions: + 
- key: role + 
operator: In + 
values: + 
- frontend
a| 

a| `extraEgress`
| @param networkPolicy.extraEgress [array] Add extra ingress rules to the NetworkPolicy + 
e.g: + 
extraEgress: + 
- ports: + 
- port: 1234 + 
to: + 
- podSelector: + 
- matchLabels: + 
- role: frontend + 
- podSelector: + 
- matchExpressions: + 
- key: role + 
operator: In + 
values: + 
- frontend
a| 

|===


===== networkPolicy.ingressNSMatchLabels

@param networkPolicy.ingressNSMatchLabels [object] Labels to match to allow traffic from other namespaces + 
@param networkPolicy.ingressNSPodMatchLabels [object] Pod labels to match to allow traffic from other namespaces




===== networkPolicy.ingressNSPodMatchLabels







==== serviceAccount

@section RBAC parameter + 
Specifies whether a ServiceAccount should be created

|===

| Name | Description | Default value

a| `create`
| @param serviceAccount.create Enable the creation of a ServiceAccount for Keycloak pods
a| true

a| `name`
| @param serviceAccount.name Name of the created ServiceAccount + 
If not set and create is true, a name is generated using the fullname template
a| 

a| `automountServiceAccountToken`
| @param serviceAccount.automountServiceAccountToken Auto-mount the service account token in the pod
a| false

|===


===== serviceAccount.annotations

@param serviceAccount.annotations Additional custom annotations for the ServiceAccount




===== serviceAccount.extraLabels

@param serviceAccount.extraLabels Additional labels for the ServiceAccount





==== rbac

Specifies whether RBAC resources should be created

|===

| Name | Description | Default value

a| `create`
| @param rbac.create Whether to create and use RBAC resources or not
a| false

a| `rules`
| @param rbac.rules Custom RBAC rules + 
Example: + 
rules: + 
- apiGroups: + 
- "" + 
resources: + 
- pods + 
verbs: + 
- get + 
- list
a| 

|===



==== pdb

@section Other parameters + 
Keycloak Pod Disruption Budget configuration + 
ref: https://kubernetes.io/docs/tasks/run-application/configure-pdb/

|===

| Name | Description | Default value

a| `create`
| @param pdb.create Enable/disable a Pod Disruption Budget creation
a| true

a| `minAvailable`
| @param pdb.minAvailable Minimum number/percentage of pods that should remain scheduled
a| 

a| `maxUnavailable`
| @param pdb.maxUnavailable Maximum number/percentage of pods that may be made unavailable
a| 

|===



==== autoscaling

Keycloak Autoscaling configuration + 
ref: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/ + 
@param autoscaling.enabled Enable autoscaling for Keycloak + 
@param autoscaling.minReplicas Minimum number of Keycloak replicas + 
@param autoscaling.maxReplicas Maximum number of Keycloak replicas + 
@param autoscaling.targetCPU Target CPU utilization percentage + 
@param autoscaling.targetMemory Target Memory utilization percentage

|===

| Name | Description | Default value

a| `enabled`
| 
a| false

a| `minReplicas`
| 
a| 1

a| `maxReplicas`
| 
a| 11

a| `targetCPU`
| 
a| 

a| `targetMemory`
| 
a| 

|===


===== autoscaling.behavior

HPA Scaling Behavior + 
configurable-scaling-behavior



====== autoscaling.behavior.scaleUp

HPA behavior when scaling up + 
@param autoscaling.behavior.scaleUp.stabilizationWindowSeconds The number of seconds for which past recommendations should be considered while scaling up + 
@param autoscaling.behavior.scaleUp.selectPolicy The priority of policies that the autoscaler will apply when scaling up + 
@param autoscaling.behavior.scaleUp.policies [array] HPA scaling policies when scaling up + 
e.g: + 
Policy to scale 20% of the pod in 60s + 
- type: Percent + 
value: 20 + 
periodSeconds: 60

|===

| Name | Description | Default value

a| `stabilizationWindowSeconds`
| 
a| 120

a| `selectPolicy`
| 
a| Max

a| `policies`
| 
a| 

|===



====== autoscaling.behavior.scaleDown

HPA behavior when scaling down + 
@param autoscaling.behavior.scaleDown.stabilizationWindowSeconds The number of seconds for which past recommendations should be considered while scaling down + 
@param autoscaling.behavior.scaleDown.selectPolicy The priority of policies that the autoscaler will apply when scaling down + 
@param autoscaling.behavior.scaleDown.policies [array] HPA scaling policies when scaling down + 
e.g: + 
Policy to scale one pod in 300s + 
- type: Pods + 
value: 1 + 
periodSeconds: 300

|===

| Name | Description | Default value

a| `stabilizationWindowSeconds`
| 
a| 300

a| `selectPolicy`
| 
a| Max

a| `policies`
| 
a| -type
-value
-periodSeconds

|===





==== metrics

@section Metrics parameters + 
Metrics configuration



===== metrics.service

Keycloak metrics service parameters



====== metrics.service.ports

@param metrics.service.ports.http Metrics service HTTP port




====== metrics.service.annotations

@param metrics.service.annotations [object] Annotations for enabling prometheus to access the metrics endpoints

|===

| Name | Description | Default value

a| `prometheus.io/scrape`
| 
a| true

a| `prometheus.io/port`
| 
a| {{ .Values.metrics.service.ports.http }}

|===




===== metrics.serviceMonitor

Prometheus Operator ServiceMonitor configuration

|===

| Name | Description | Default value

a| `enabled`
| @param metrics.serviceMonitor.enabled Create ServiceMonitor Resource for scraping metrics using PrometheusOperator
a| false

a| `port`
| @param metrics.serviceMonitor.port Metrics service HTTP port
a| http

a| `endpoints`
| @param metrics.serviceMonitor.endpoints [array] The endpoint configuration of the ServiceMonitor. Path is mandatory. Interval, timeout and labellings can be overwritten.
a| -path
-path

a| `path`
| @param metrics.serviceMonitor.path Metrics service HTTP path. Deprecated: Use @param metrics.serviceMonitor.endpoints instead
a| 

a| `namespace`
| @param metrics.serviceMonitor.namespace Namespace which Prometheus is running in
a| 

a| `interval`
| @param metrics.serviceMonitor.interval Interval at which metrics should be scraped
a| 30s

a| `scrapeTimeout`
| @param metrics.serviceMonitor.scrapeTimeout Specify the timeout after which the scrape is ended + 
e.g: + 
scrapeTimeout: 30s
a| 

a| `relabelings`
| @param metrics.serviceMonitor.relabelings RelabelConfigs to apply to samples before scraping
a| 

a| `metricRelabelings`
| @param metrics.serviceMonitor.metricRelabelings MetricRelabelConfigs to apply to samples before ingestion
a| 

a| `honorLabels`
| @param metrics.serviceMonitor.honorLabels honorLabels chooses the metric's labels on collisions with target labels
a| false

a| `jobLabel`
| @param metrics.serviceMonitor.jobLabel The name of the label on the target service to use as the job name in prometheus.
a| 

|===


====== metrics.serviceMonitor.labels

@param metrics.serviceMonitor.labels Additional labels that can be used so ServiceMonitor will be discovered by Prometheus




====== metrics.serviceMonitor.selector

@param metrics.serviceMonitor.selector Prometheus instance selector labels + 
prometheus-configuration





===== metrics.prometheusRule

Prometheus Operator alert rules configuration

|===

| Name | Description | Default value

a| `enabled`
| @param metrics.prometheusRule.enabled Create PrometheusRule Resource for scraping metrics using PrometheusOperator
a| false

a| `namespace`
| @param metrics.prometheusRule.namespace Namespace which Prometheus is running in
a| 

a| `groups`
| @param metrics.prometheusRule.groups Groups, containing the alert rules. + 
Example: + 
groups: + 
- name: Keycloak + 
rules: + 
- alert: KeycloakInstanceNotAvailable + 
annotations: + 
message: "Keycloak instance in namespace {{ `{{` }} $labels.namespace {{ `}}` }} has not been available for the last 5 minutes." + 
expr: \| + 
absent(kube_pod_status_ready{namespace="{{ include "common.names.namespace" . }}", condition="true"} * on (pod) kube_pod_labels{pod=~"{{ include "common.names.fullname" . }}-\\d+", namespace="{{ include "common.names.namespace" . }}"}) != 0 + 
for: 5m + 
labels: + 
severity: critical
a| 

|===


====== metrics.prometheusRule.labels

@param metrics.prometheusRule.labels Additional labels that can be used so PrometheusRule will be discovered by Prometheus






==== keycloakConfigCli

@section keycloak-config-cli parameters + 
Configuration for keycloak-config-cli + 
ref: https://github.com/adorsys/keycloak-config-cli

|===

| Name | Description | Default value

a| `enabled`
| @param keycloakConfigCli.enabled Whether to enable keycloak-config-cli job
a| false

a| `command`
| @param keycloakConfigCli.command Command for running the container (set to default if not set). Use array form
a| 

a| `args`
| @param keycloakConfigCli.args Args for running the container (set to default if not set). Use array form
a| 

a| `automountServiceAccountToken`
| @param keycloakConfigCli.automountServiceAccountToken Mount Service Account token in pod
a| true

a| `hostAliases`
| @param keycloakConfigCli.hostAliases Job pod host aliases + 
https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/
a| 

a| `resourcesPreset`
| Keycloak config CLI resource requests and limits + 
ref: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/ + 
@param keycloakConfigCli.resourcesPreset Set container resources according to one common preset (allowed values: none, nano, micro, small, medium, large, xlarge, 2xlarge). This is ignored if keycloakConfigCli.resources is set (keycloakConfigCli.resources is recommended for production). + 
L15
a| small

a| `backoffLimit`
| @param keycloakConfigCli.backoffLimit Number of retries before considering a Job as failed + 
pod-backoff-failure-policy
a| 1

a| `podTolerations`
| @param keycloakConfigCli.podTolerations Tolerations for job pod assignment + 
ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
a| 

a| `extraEnvVars`
| 
a| 

a| `extraEnvVarsCM`
| @param keycloakConfigCli.extraEnvVarsCM ConfigMap with extra environment variables
a| 

a| `extraEnvVarsSecret`
| @param keycloakConfigCli.extraEnvVarsSecret Secret with extra environment variables
a| 

a| `extraVolumes`
| @param keycloakConfigCli.extraVolumes Extra volumes to add to the job
a| 

a| `extraVolumeMounts`
| @param keycloakConfigCli.extraVolumeMounts Extra volume mounts to add to the container
a| 

a| `initContainers`
| @param keycloakConfigCli.initContainers Add additional init containers to the Keycloak config cli pod + 
Example: + 
initContainers: + 
- name: your-image-name + 
image: your-image + 
imagePullPolicy: Always + 
ports: + 
- name: portname + 
containerPort: 1234
a| 

a| `sidecars`
| @param keycloakConfigCli.sidecars Add additional sidecar containers to the Keycloak config cli pod + 
Example: + 
sidecars: + 
- name: your-image-name + 
image: your-image + 
imagePullPolicy: Always + 
ports: + 
- name: portname + 
containerPort: 1234
a| 

a| `existingConfigmap`
| @param keycloakConfigCli.existingConfigmap ConfigMap with keycloak-config-cli configuration + 
NOTE: This will override keycloakConfigCli.configuration
a| 

|===


===== keycloakConfigCli.image

Bitnami keycloak-config-cli image + 
ref: https://hub.docker.com/r/bitnami/keycloak-config-cli/tags/ + 
@param keycloakConfigCli.image.registry [default: REGISTRY_NAME] keycloak-config-cli container image registry + 
@param keycloakConfigCli.image.repository [default: REPOSITORY_NAME/keycloak-config-cli] keycloak-config-cli container image repository + 
@skip keycloakConfigCli.image.tag keycloak-config-cli container image tag + 
@param keycloakConfigCli.image.digest keycloak-config-cli container image digest in the way sha256:aa.... Please note this parameter, if set, will override the tag + 
@param keycloakConfigCli.image.pullPolicy keycloak-config-cli container image pull policy + 
@param keycloakConfigCli.image.pullSecrets keycloak-config-cli container image pull secrets

|===

| Name | Description | Default value

a| `registry`
| 
a| docker.io

a| `repository`
| 
a| bitnami/keycloak-config-cli

a| `tag`
| 
a| 6.1.6-debian-12-r0

a| `digest`
| 
a| 

a| `pullPolicy`
| Specify a imagePullPolicy + 
Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent' + 
pre-pulled-images
a| IfNotPresent

a| `pullSecrets`
| Optionally specify an array of imagePullSecrets. + 
Secrets must be manually created in the namespace. + 
ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/ + 
e.g: + 
pullSecrets: + 
- myRegistryKeySecretName
a| 

|===



===== keycloakConfigCli.annotations

@param keycloakConfigCli.annotations [object] Annotations for keycloak-config-cli job + 
ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/

|===

| Name | Description | Default value

a| `helm.sh/hook`
| 
a| post-install,post-upgrade,post-rollback

a| `helm.sh/hook-delete-policy`
| 
a| hook-succeeded,before-hook-creation

a| `helm.sh/hook-weight`
| 
a| 5

|===



===== keycloakConfigCli.resources

@param keycloakConfigCli.resources Set container requests and limits for different resources like CPU or memory (essential for production workloads) + 
Example: + 
resources: + 
requests: + 
cpu: 2 + 
memory: 512Mi + 
limits: + 
cpu: 3 + 
memory: 1024Mi




===== keycloakConfigCli.containerSecurityContext

keycloak-config-cli containers' Security Context + 
set-the-security-context-for-a-container + 
@param keycloakConfigCli.containerSecurityContext.enabled Enabled keycloak-config-cli Security Context + 
@param keycloakConfigCli.containerSecurityContext.seLinuxOptions [object,nullable] Set SELinux options in container + 
@param keycloakConfigCli.containerSecurityContext.runAsUser Set keycloak-config-cli Security Context runAsUser + 
@param keycloakConfigCli.containerSecurityContext.runAsGroup Set keycloak-config-cli Security Context runAsGroup + 
@param keycloakConfigCli.containerSecurityContext.runAsNonRoot Set keycloak-config-cli Security Context runAsNonRoot + 
@param keycloakConfigCli.containerSecurityContext.privileged Set keycloak-config-cli Security Context privileged + 
@param keycloakConfigCli.containerSecurityContext.readOnlyRootFilesystem Set keycloak-config-cli Security Context readOnlyRootFilesystem + 
@param keycloakConfigCli.containerSecurityContext.allowPrivilegeEscalation Set keycloak-config-cli Security Context allowPrivilegeEscalation + 
@param keycloakConfigCli.containerSecurityContext.capabilities.drop List of capabilities to be dropped + 
@param keycloakConfigCli.containerSecurityContext.seccompProfile.type Set keycloak-config-cli Security Context seccomp profile

|===

| Name | Description | Default value

a| `enabled`
| 
a| true

a| `runAsUser`
| 
a| 1001

a| `runAsGroup`
| 
a| 1001

a| `runAsNonRoot`
| 
a| true

a| `privileged`
| 
a| false

a| `readOnlyRootFilesystem`
| 
a| true

a| `allowPrivilegeEscalation`
| 
a| false

|===


====== keycloakConfigCli.containerSecurityContext.seLinuxOptions






====== keycloakConfigCli.containerSecurityContext.capabilities






====== keycloakConfigCli.containerSecurityContext.seccompProfile







===== keycloakConfigCli.podSecurityContext

keycloak-config-cli pods' Security Context + 
set-the-security-context-for-a-pod + 
@param keycloakConfigCli.podSecurityContext.enabled Enabled keycloak-config-cli pods' Security Context + 
@param keycloakConfigCli.podSecurityContext.fsGroupChangePolicy Set filesystem group change policy + 
@param keycloakConfigCli.podSecurityContext.sysctls Set kernel settings using the sysctl interface + 
@param keycloakConfigCli.podSecurityContext.supplementalGroups Set filesystem extra groups + 
@param keycloakConfigCli.podSecurityContext.fsGroup Set keycloak-config-cli pod's Security Context fsGroup

|===

| Name | Description | Default value

a| `enabled`
| 
a| true

a| `fsGroupChangePolicy`
| 
a| Always

a| `sysctls`
| 
a| 

a| `supplementalGroups`
| 
a| 

a| `fsGroup`
| 
a| 1001

|===



===== keycloakConfigCli.podLabels

@param keycloakConfigCli.podLabels Pod extra labels + 
ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/




===== keycloakConfigCli.podAnnotations

@param keycloakConfigCli.podAnnotations Annotations for job pod + 
ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/




===== keycloakConfigCli.nodeSelector

@param keycloakConfigCli.extraEnvVars Additional environment variables to set + 
Example: + 
extraEnvVars: + 
- name: FOO + 
value: "bar" + 
@param keycloakConfigCli.nodeSelector Node labels for pod assignment + 
ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/




===== keycloakConfigCli.configuration

@param keycloakConfigCli.configuration keycloak-config-cli realms configuration + 
NOTE: nil keys will be considered files to import locally + 
Example: + 
configuration: + 
realm1.json: \| + 
{ + 
"realm": "realm1", + 
"clients": [] + 
} + 
realm2.yaml: \| + 
realm: realm2 + 
clients: []




===== keycloakConfigCli.cleanupAfterFinished

Automatic Cleanup for Finished Jobs + 
@param keycloakConfigCli.cleanupAfterFinished.enabled Enables Cleanup for Finished Jobs + 
@param keycloakConfigCli.cleanupAfterFinished.seconds Sets the value of ttlSecondsAfterFinished + 
ref: https://kubernetes.io/docs/concepts/workloads/controllers/ttlafterfinished/

|===

| Name | Description | Default value

a| `enabled`
| 
a| false

a| `seconds`
| 
a| 600

|===




==== postgresql

@section Database parameters + 
PostgreSQL chart configuration + 
ref: https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.yaml + 
@param postgresql.enabled Switch to enable or disable the PostgreSQL helm chart + 
@param postgresql.auth.postgresPassword Password for the "postgres" admin user. Ignored if `auth.existingSecret` with key `postgres-password` is provided + 
@param postgresql.auth.username Name for a custom user to create + 
@param postgresql.auth.password Password for the custom user to create + 
@param postgresql.auth.database Name for a custom database to create + 
@param postgresql.auth.existingSecret Name of existing secret to use for PostgreSQL credentials + 
@param postgresql.architecture PostgreSQL architecture (`standalone` or `replication`)

|===

| Name | Description | Default value

a| `enabled`
| 
a| true

a| `architecture`
| 
a| standalone

|===


===== postgresql.auth



|===

| Name | Description | Default value

a| `postgresPassword`
| 
a| 

a| `username`
| 
a| bn_keycloak

a| `password`
| 
a| 

a| `database`
| 
a| bitnami_keycloak

a| `existingSecret`
| 
a| 

|===




==== externalDatabase

External PostgreSQL configuration + 
All of these values are only used when postgresql.enabled is set to false + 
@param externalDatabase.host Database host + 
@param externalDatabase.port Database port number + 
@param externalDatabase.user Non-root username for Keycloak + 
@param externalDatabase.password Password for the non-root username for Keycloak + 
@param externalDatabase.database Keycloak database name + 
@param externalDatabase.existingSecret Name of an existing secret resource containing the database credentials + 
@param externalDatabase.existingSecretHostKey Name of an existing secret key containing the database host name + 
@param externalDatabase.existingSecretPortKey Name of an existing secret key containing the database port + 
@param externalDatabase.existingSecretUserKey Name of an existing secret key containing the database user + 
@param externalDatabase.existingSecretDatabaseKey Name of an existing secret key containing the database name + 
@param externalDatabase.existingSecretPasswordKey Name of an existing secret key containing the database credentials + 
@param externalDatabase.annotations Additional custom annotations for external database secret object

|===

| Name | Description | Default value

a| `host`
| 
a| 

a| `port`
| 
a| 5432

a| `user`
| 
a| bn_keycloak

a| `database`
| 
a| bitnami_keycloak

a| `password`
| 
a| 

a| `existingSecret`
| 
a| 

a| `existingSecretHostKey`
| 
a| 

a| `existingSecretPortKey`
| 
a| 

a| `existingSecretUserKey`
| 
a| 

a| `existingSecretDatabaseKey`
| 
a| 

a| `existingSecretPasswordKey`
| 
a| 

|===


===== externalDatabase.annotations







==== cache

@section Keycloak Cache parameters + 
Keycloak cache configuration + 
ref: https://www.keycloak.org/server/caching + 
@param cache.enabled Switch to enable or disable the keycloak distributed cache for kubernetes. + 
NOTE: Set to false to use 'local' cache (only supported when replicaCount=1). + 
@param cache.stackName Set infinispan cache stack to use + 
@param cache.stackFile Set infinispan cache stack filename to use

|===

| Name | Description | Default value

a| `enabled`
| 
a| true

a| `stackName`
| 
a| kubernetes

a| `stackFile`
| 
a| 

|===



==== logging

@section Keycloak Logging parameters + 
Keycloak logging configuration + 
ref: https://www.keycloak.org/server/logging + 
@param logging.output Alternates between the default log output format or json format + 
@param logging.level Allowed values as documented: FATAL, ERROR, WARN, INFO, DEBUG, TRACE, ALL, OFF

|===

| Name | Description | Default value

a| `output`
| 
a| default

a| `level`
| 
a| INFO

|===



