{@com.github.jtama.Chart chart}
= {chart.name}
:hardbreaks-option:

{chart.description}

== Identity card

[horizontal]

*apiVersion*: {chart.apiVersion}
*version*: {chart.version}
{#if chart.kubeVersion != null}
*kubeVersion*: {chart.kubeVersion}
{/if}
{#if chart.type != null}
*type*: {chart.type}
{/if}
{#if chart.keywords.size() > 0}
*keywords* :
{#for keyword in chart.keywords}
\{nbsp\} - {keyword}
{/for}
{/if}
{#if chart.home != null}
*home*: {chart.home}
{/if}
{#if chart.sources.size() > 0}
*sources* :
{#for source in chart.sources}
* {source}
{/for}
{/if}
{#include dependencies.adoc dependencies=chart.dependencies/}
{#if chart.maintainers.size() > 0}
*maintainers*:
{#for maintainer in chart.maintainers}
\{nbsp\} - {maintainer.name} {#if maintainer.email != null}, {maintainer.email}{/if}{#if maintainer.url != null}, {maintainer.url}{/if}
{/for}
{/if}
{#if chart.icon != null}
*icon*: image:{chart.icon}[width=48]
{/if}
{#if chart.appVersion != null}
*appVersion*: {chart.appVersion}
{/if}
*deprecated*: {chart.deprecated}
{#if chart.annotations.size() > 0}
*annotations* :
{#for annotation in chart.annotations}
\{nbsp\} - {annotation.key}:  {annotation.value ?: ''}
{/for}
{/if}

== Chart values

{#for section in chart.sections}

{#include section.adoc level='===' section=section /}

{/for}

{#if includeRaw}
{#include appendix.adoc/}
{/if}